// <auto-generated />
using System;
using IntegracaoCepsaBrasil.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntegracaoCepsaBrasil.Data.Migrations
{
    [DbContext(typeof(CEPSADbContext))]
    [Migration("20240926012300_AjusteCamposString")]
    partial class AjusteCamposString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IntegracaoCepsaBrasil.Data.Models.DatosSindicales", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustCodigoDoSindicato")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cust_CodigoDoSindicato");

                    b.Property<string>("CustIndicadorDeSindicalizado")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cust_IndicadorDeSindicalizado");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("externalCode");

                    b.Property<DateTime?>("LastModifiedDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastModifiedDateTime");

                    b.HasKey("Id");

                    b.ToTable("DatosSindicales");
                });

            modelBuilder.Entity("IntegracaoCepsaBrasil.Data.Models.EmpJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("company");

                    b.Property<string>("ContractType")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("contractType");

                    b.Property<string>("CostCenter")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("costCenter");

                    b.Property<string>("CustomString150")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString150");

                    b.Property<string>("CustomString151")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString151");

                    b.Property<string>("CustomString152")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString152");

                    b.Property<string>("CustomString153")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString153");

                    b.Property<string>("CustomString154")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString154");

                    b.Property<string>("CustomString155")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString155");

                    b.Property<string>("CustomString156")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString156");

                    b.Property<string>("CustomString157")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString157");

                    b.Property<string>("CustomString159")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString159");

                    b.Property<string>("CustomString160")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString160");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("LastModifiedOn")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("lastModifiedOn");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("userId");

                    b.Property<string>("WorkerCategory")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("workerCategory");

                    b.HasKey("Id");

                    b.ToTable("EmpJob");
                });

            modelBuilder.Entity("IntegracaoCepsaBrasil.Data.Models.FiscalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustDTEmissaoDoTitulo")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cust_DTEmissaoDoTitulo");

                    b.Property<string>("CustNTituloDeEleitor")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cust_NTituloDeEleitor");

                    b.Property<string>("CustSecaoDoTituloDeEleitor")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cust_SecaoDoTituloDeEleitor");

                    b.Property<string>("CustUFDoTituloDeEleitor")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cust_UFDoTituloDeEleitor");

                    b.Property<string>("CustZonaDoTituloDeEleitor")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("cust_ZonaDoTituloDeEleitor");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("ExternalCode")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("externalCode");

                    b.Property<string>("LastModifiedDateTime")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("lastModifiedDateTime");

                    b.HasKey("Id");

                    b.ToTable("FiscalData");
                });

            modelBuilder.Entity("IntegracaoCepsaBrasil.Data.Models.PerAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address1");

                    b.Property<string>("Address2")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address2");

                    b.Property<string>("Address3")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address3");

                    b.Property<string>("Address4")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("address4");

                    b.Property<string>("Company")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("company");

                    b.Property<string>("CustomString2")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("PersonIdExternal")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("personIdExternal");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("userId");

                    b.Property<string>("ZipCode")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("zipCode");

                    b.HasKey("Id");

                    b.ToTable("PerAddress");
                });

            modelBuilder.Entity("IntegracaoCepsaBrasil.Data.Models.PerEmail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("company");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("EmailAddress")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("emailAddress");

                    b.Property<string>("EmailType")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("emailType");

                    b.Property<string>("PersonIdExternal")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("personIdExternal");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.ToTable("PerEmail");
                });

            modelBuilder.Entity("IntegracaoCepsaBrasil.Data.Models.PerPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("company");

                    b.Property<string>("CustomString4")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString4");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("dateOfBirth");

                    b.Property<string>("EndDate")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("endDate");

                    b.Property<string>("LastModifiedOn")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("lastModifiedOn");

                    b.Property<string>("PersonIdExternal")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("personIdExternal");

                    b.Property<string>("StartDate")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("startDate");

                    b.HasKey("Id");

                    b.ToTable("PerPerson");
                });

            modelBuilder.Entity("IntegracaoCepsaBrasil.Data.Models.PerPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("company");

                    b.Property<string>("CustomString2")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString2");

                    b.Property<string>("CustomString7")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("customString7");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Gender")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("gender");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastModifiedOn");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("maritalStatus");

                    b.Property<string>("Nationality")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("nationality");

                    b.Property<string>("PersonIdExternal")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("personIdExternal");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.Property<string>("UserId")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("userId");

                    b.HasKey("Id");

                    b.ToTable("PerPersonal");
                });

            modelBuilder.Entity("IntegracaoCepsaBrasil.Data.Models.PerPhone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaCode")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("AreaCode");

                    b.Property<string>("BusinessPhone")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("businessPhone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Extension")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("Extension");

                    b.Property<string>("PersonIdExernal")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("personIdExernal");

                    b.Property<string>("PersonalPhone")
                        .HasColumnType("varchar(max)")
                        .HasColumnName("personalPhone");

                    b.HasKey("Id");

                    b.ToTable("PerPhone");
                });
#pragma warning restore 612, 618
        }
    }
}
